# Generated by Django 5.1.6 on 2025-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='hiredate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
