# Generated by Django 5.1.6 on 2025-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_appointment_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=50)),
                ('YourEmail', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
    ]
